### ISSUE TITLE
AbstractCapabilityProfile

### ISSUE THREAD

**Issue by webnapier** [mike42/escpos-php#47] opened 2015-08-11 22:45 UTC
I'm using the library ESCPOS-php. What code I'm using is this:

<? php
require_once (dirname (__ FILE__) "/Escpos.php.");
$ connector = new WindowsPrintConnector ("POS58");
$ printer = new ESCPOS ($ connector);
$ printer -> text ("Hello World! \ n");
$ printer -> cut ();
$ printer -> close ();
?>

I'm working locally with USB thermal printer under Windows 7 with PHP 5.2.17 . When you run the script I get this error:

[11-Aug-2015 19:58:37] PHP Parse error: syntax error, unexpected T_STATIC, expecting T_STRING or T_VARIABLE or '$' in C: \ Apache2.2 \ htdocs \ metropolis \ src \ AbstractCapabilityProfile.php on line 57
 
There are some installation manual to solve this error.

**Comment by zcastle** [comment] 2015-08-11 22:48
Use $printer without space

**Comment by mike42** [comment] 2015-08-13 10:03
As noted by email, this appears to be a duplicate of #34, and it looks like upgrading fixed it, per #48

**Closed by mike42** 2015-08-13 10:03 UTC
Labels: duplicate
