### ISSUE TITLE
How to print chinese?

### ISSUE THREAD

**Issue by junezhou** [mike42/escpos-php#63] opened 2015-10-22 05:47 UTC
How to print chinese?
utf8

**Comment by mike42** [comment] 2015-10-24 22:23
This is not currently supported, but there is a lot of interest in it over at #37, and somebody has their printer working by replacing my UTF8 wrangler with a one-line UTF-8 to GBK conversion.

Can you let me know-
- Printer manufacturer & model
- Printer interface (USB/Serial/Ethernet).
- Are you trying to print traditional or simplified characters?

**Comment by mike42** [comment] 2016-03-14 04:41
No extra info here, closing as duplicate of #37

**Closed by mike42** 2016-03-14 04:41 UTC
Labels: duplicate, enhancement
