### ISSUE TITLE
Bar Code Printer T-9650 Plus - PHP Printer 

### ISSUE THREAD

**Issue by andrewsducloux** [mike42/escpos-php#419] opened 2017-08-30 06:23 UTC
Am using Bar Code Printer T-9650 Plus
for Barcode Generator, this printer is not working with your helper. May i know someother source to use this.

And Printing in Tamil Language is not working, please suggest me for printing bill in tamil for Epson Printer

**Comment by mike42** [comment] 2017-10-22 06:26
Closing as duplicate of #418

**Closed by mike42** 2017-10-22 06:26 UTC
