### ISSUE TITLE
cut() not work in "Star TSP-700ii"

### ISSUE THREAD

**Issue by edisla1992** [mike42/escpos-php#163] opened 2016-08-31 23:39 UTC

**Comment by edisla1992** [comment] 2016-08-31 23:39
send email please edisla1992@gmail.com

**Comment by mike42** [comment] 2016-09-03 00:36
Hey, I will be responding on the issue tracker, so that people with similar issues can search here for answers.

I could use some more specific information in order to debug this, as I don't have one of these printers to try it out myself.

- What does 'not work' mean? (eg, nothing happens but the printer keeps working, it hangs, it prints garbage, etc)
- Is it safe for me to assume that your printer does have a working auto-cutter?
- Do you have a link to vendor docs with the command for triggering the auto-cutter on this printer?
- Can you share a snippet of how you're printing, so that I can confirm that you are initialising the printer correctly?

I may just need to add a different cut command for this model of printer, but if you can answer all this, then I can hopefully be sure what's wrong, fix it, and post back a snippet to test.

**Comment by mike42** [comment] 2016-11-04 13:53
I'll close this issue off if there is no response in the next few days.

A quick Google search turns up this [Star ESC/POS emulation](http://www.starmicronics.com/support/mannualfolder/escpos_cm_en.pdf) documentation, that shows `GS V m n` as available on this model of printer. This is the command used by `cut()`.

**Comment by gianweb** [comment] 2016-12-22 16:53
Good morning, it says in your documentation that it works with a TSP 100, because I connect by smbd and I work the printer but the cutting theme, does not work on top of Hello World VA!, In conclusion do not cut the page please help me

**Comment by mike42** [comment] 2017-01-22 01:16
Closing this off as abandoned.

@edisla1992 - Please post a follow-up issue with more information about your setup if believe you have found a bug in escpos-php. See [the above comment](https://github.com/mike42/escpos-php/issues/163#issuecomment-244515842) for the sort of info that is missing from this issue.

@gianweb - You don't have the same printer, and I don't know if your problem is the same as OP. If you believe that the you are seeing is a bug in escpos-php, then please post a separate issue showing detailed information about what you tried (printer configuration, ESC/POS mode, PHP snippet), what you expected to happen, and what happened instead.

**Closed by mike42** 2017-01-22 01:16 UTC
Labels: needs info, printer-compatibility
