### ISSUE TITLE
Greek symbol swap

### ISSUE THREAD

**Issue by p3110145** [mike42/escpos-php#62] opened 2015-10-21 09:23 UTC
The capital greek letter 'Μ' swaps with 'Ν' and vice versa.

**Comment by p3110145** [comment] 2015-10-21 09:25
Could it be caused by the Characters-DefaultCapabilityProfile.ser file?

**Comment by mike42** [comment] 2015-10-21 09:35
Thanks for the report. There are a few ways that Greek characters could be generated, and that `.ser` file is simply an auto-generated cache (the PrintBuffer is where the logic is).

So that I can replicated-
- Can you provide a minimal code snippet which demonstrates this bug, and a description of expected vs. actual output? (a scan or photo of the receipt is useful in case it appears different to my my TM-T20)
- What printer make & model do you use?
- What OS are you on? (if linux, can you paste in the output of `iconv -l`?)

**Comment by p3110145** [comment] 2015-10-21 10:01
https://gist.github.com/p3110145/acbdbf3b7d166ce292fd
outputs "Νιχάλης Μίκος".

The printer is TM-T20II.

iconv: https://gist.github.com/p3110145/f4869c868e709d38e9b1

**Comment by p3110145** [comment] 2015-10-21 11:02
Coverting to ISO-8859-7 from UTF-8  using mb_convert_encoding and printing with textRaw works fine.
Is loadAvailableCharacters the key function?

**Comment by mike42** [comment] 2015-10-21 11:03
Confirmed, you've found a bug. Good use of `textRaw` to bypass this madness.

**Comment by p3110145** [comment] 2015-10-21 11:09
This is how I managed to solve it.
https://gist.github.com/p3110145/6d85c78eb9821936c9a8
Is there any better solution?

**Comment by mike42** [comment] 2016-04-23 15:05
This has been quite a tricky bug, but I believe it is now resolved in the current `testing` branch.

Short story is, you can run this snippet:

```php
<?php
require __DIR__ . '/../../autoload.php';
use Mike42\Escpos\Printer;
use Mike42\Escpos\PrintConnectors\FilePrintConnector;
use Mike42\Escpos\CapabilityProfiles\DefaultCapabilityProfile;

$connector = new FilePrintConnector("php://stdout");
$profile = DefaultCapabilityProfile::getInstance();
$printer = new Printer($connector, $profile);

$printer -> text("Μιχάλης Νίκος\n");
$printer -> cut();
$printer -> close();

?>
```

And get this output (tested on TM-T20):

![2016-04-issue-62-1](https://cloud.githubusercontent.com/assets/2080552/14762023/1f1a67f0-09b4-11e6-9405-fd87ed75fa77.png)

### Bug identification
I analysed the buggy output with an ESC/POS parser that I'm working on ([link](https://github.com/mike42/escpos-snippets/tree/master/parser)), and found that it was printing using character set 11 on my printer, which is CP851. From `DefaultCapabilityProfile.php`:

```php
11 => CodePage::CP851,
...
15 => CodePage::ISO8859_7,
```

So I printed out the code page using `character-tables.php`:

![2016-04-issue-62-2](https://cloud.githubusercontent.com/assets/2080552/14762103/b2371852-09b5-11e6-8d29-10a1b5033ce0.png)

This checks out against the [Epson docs](https://reference.epson-biz.com/modules/ref_charcode_en/index.php?content_id=21), [Wikipedia](https://en.wikipedia.org/wiki/Code_page_851), and [this](https://msdn.microsoft.com/en-us/library/cc195065.aspx) Microsoft source, so I'm sure I've matched up the code pages correctly.

Noticing that I can print using `iconv("UTF-8", "ISO-8859-7", "Μιχάλης Νίκος\n")` but not `iconv("UTF-8", "CP851", "Μιχάλης Νίκος\n")`, I dug a bit deeper into `iconv`, and found the culprit in a file called  `IBM851` in the `glibc` source.

This file lists the letters in a different order:

```
%  source: IBM NLS RM Vol2 SE09-8002-01, March 1990
% alias CP851
...
<U039D>     /xb7         GREEK CAPITAL LETTER NU
<U039C>     /xb8         GREEK CAPITAL LETTER MU
```

And I can see that this is definitely what's happening with this quick test:
```php
<?php
echo iconv("UTF-8", "CP851", "ΜΝ\n");
```

```php
$ php test.php | hexdump -C
00000000  b8 b7 0a                                          |...|
00000003
```

(b8 and b7, if you look them up on the table that the printer spat out, are ΝΜ, not ΜΝ). Clearly `glibc` has a bug, right? Before filing a bug, I checked their sources.

This file cites an IBM standard doc, which I can't find, but [rfc1345](http://tools.ietf.org/html/rfc1345) lists the same characters (page 88) with this source, so there are two competing definitions of this obsolete code page in the wild.

Because of this incompatibility, I've pulled out `CP851` from the driver. The other Greek code pages on the TM-T20 provide enough support for your use case.

There is some work around the CapabilityProfile system pending, but I hope to have the ESC/POS-compatible version of CP851 added in at some point in the future.

**Closed** 2016-04-25 01:14 UTC
Labels: bug
