### ISSUE TITLE
Fatal error

### ISSUE THREAD

**Issue by matiasgaston** [mike42/escpos-php#86] opened 2016-02-26 01:31 UTC
Sorry to bother you, I'm new to this proyect.

I have the following problem;

"Fatal error: Class 'Mike42\Escpos\Printer' not found in D:\xampp\htdocs\printer\public\src\hello-world.php on line 4"

how i can fix?

Best regards.

**Comment by barayuda** [comment] 2016-02-26 05:46
Hello @matiasgaston 
I think error from include the class to your project.
Can you share the screenshot from line 4?

**Comment by matiasgaston** [comment] 2016-02-26 05:59
i try to test this code:
<?php
require '../../vendor/autoload.php';
use Mike42\Escpos\Printer;
$printer = new Printer();
$printer -> text("Hello World!\n");
$printer -> cut();
$printer -> close();
?>

**Comment by matiasgaston** [comment] 2016-02-26 14:43
the error has been fixed, but now show me another error.

Fatal error: Uncaught exception 'InvalidArgumentException' with message 'Argument passed to Printer::__construct() must implement interface PrintConnector, null given.' in D:\xampp\htdocs\printer\public\src\Mike42\Escpos\Printer.php:172 Stack trace: #0 D:\xampp\htdocs\printer\public\example\print-from-html.php(5): Mike42\Escpos\Printer->__construct() #1 {main} thrown in D:\xampp\htdocs\printer\public\src\Mike42\Escpos\Printer.php on line 172

**Comment by matiasgaston** [comment] 2016-02-26 15:47
solved

<?php
require __DIR__ . '/../vendor/autoload.php';
use Mike42\Escpos\Printer;
use Mike42\Escpos\PrintConnectors\FilePrintConnector;
//$printer = new Printer();
$connector = new FilePrintConnector("/dev/ttyS0");
$printer = new Printer($connector);
$printer -> text("Hello World!\n");
$printer -> cut();
$printer -> close();

**Comment by barayuda** [comment] 2016-03-03 02:31
Nice tried @matiasgaston :D
error on path

**Comment by mike42** [comment] 2016-03-14 04:19
Regarding the API to initialize the printer, this is a duplicate of #82, #18.

See also #93, an auto-loader is now bundled for users without composer.

**Closed by mike42** 2016-03-14 04:19 UTC
Labels: duplicate
