### ISSUE TITLE
TM-U220B Printing Empty Lines Instead of Image

### ISSUE THREAD

**Issue by theslowblitz** [mike42/escpos-php#125] opened 2016-05-30 04:55 UTC
Hi Mike,

Using 

`$printer -> bitImageColumnFormat($logo, Printer::IMG_DOUBLE_WIDTH | Printer::IMG_DOUBLE_HEIGHT);`

I can print every image in the example/resources folder. I can also print other images I downloaded from the web, as long as the dimensions aren't too large. But I cannot print the image I want to print, even if I change the dimensions and change the colour to B&W. I don't understand why. Do you have any advice?

**Comment by mike42** [comment] 2016-05-30 12:06
This is the correct function to call for the TM-U220B, so you're using the library correctly.

Are you able to post the image you're using here or email it so that I can try to replicate this on my TM-U220? (you can find my email [here](https://mike42.me/blog/about)). I can't say much for sure without testing this out.

It would also help to know whether each of `imagick` and `gd` extensions are loaded, and which version of PHP you are running. You can find this information via `phpinfo()` (web) or `php -m`; `php --version` (command line).

**Comment by theslowblitz** [comment] 2016-05-31 02:23
Installing imagick worked! I'm not sure why, I thought the driver was using gd. Thanks for your help!!

**Comment by mike42** [comment] 2016-06-13 04:09
OK, did some investigation, looks like there are no bugs here, but you may be able to improve the output if you edit up your image to be more printer-friendly.

- Image is too wide to print. I think the U220 is about 300px wide.
- libpng logs that the image has invalid sRGB profile ([easy to remove](http://tex.stackexchange.com/questions/125612/warning-pdflatex-libpng-warning-iccp-known-incorrect-srgb-profile))
- Image is too light. The threshold that is used in the Gd code was turning the whole image white, like so-

![image](https://cloud.githubusercontent.com/assets/2080552/15996756/b7ee85ce-316e-11e6-8f9e-889925c1afcc.png)

Thankfully, the Imagick code uses a more advanced black & white conversion, which is why changing libraries helped in your case.

I'll close this issue off as I think it's solved now.

PS: Regarding printing from a URL, I'm not sure I understand what you mean (ie, print from the web #121 or [load image externally](http://php.net/manual/en/imagick.readimagefile.php)?). If you would like to suggest it as an enhancement, you are welcome to file a new issue including some detail of what the expected behavior would be, and I may be able to identify the parts of the code which could be changed to accommodate it.

**Closed by mike42** 2016-06-13 04:09 UTC

**Comment by Georangelg** [comment] 2019-08-10 02:59
@mdestafadilah  it works like a charm hommie, tnx a lot 4 share 
the key is the way that we need to call the file path, on my case i'm working with CodeIgniter, so my solution was:

$this->path = dirname(__FILE__)."\log.png"; 
$this->img_logo = EscposImage::load($this->path, false);
 $this->printer->bitImageColumnFormat($this->img_logo, Printer::IMG_DEFAULT);


Regs Geo RG.
