### ISSUE TITLE
Is it possible to print from online hosted application to local system.

### ISSUE THREAD

**Issue by shaan360** [mike42/escpos-php#121] opened 2016-05-06 07:39 UTC
I have php based application which hosted on bluehost linux server. I want to print receipt from there. 

When i try to print i get this error 

> Failed to print. Command "smbclient '//rsb17.rhostbh.com/PRP088' -c 'print -' -N" failed with exit code 127:

On localhost print working awesome. 

Thanks

**Comment by mike42** [comment] 2016-05-26 12:01
This is not a bug, but "How can I print from the Internet?" should probably be listed in an FAQ of some sort (see also #76, #91, #100, #38).

To quote the README-

> To make use of this driver, your server (where PHP is installed) must be able to communicate with your printer. Start by generating a simple receipt and sending it to your printer using the command-line.

Remembering that this driver sends data to the printer from the server-side (ie, **not** via the web browser), you would be likely to need a secure tunnel if you are going to place the server and printer on different networks (something like VPN or SSH).

This will require some network know-how to set up, but as this is not a network support forum, I will leave the details of this to you.

Once you can send "Hello World" to your printer via the command-line on your PHP server, you are ready to plug this driver in, so that you can generate more complex commands.

Additionally, as you are getting exit code 127, it looks like your host is not equipped with an `smbclient` command. Again, you need a working way to send data to your printer before this driver will be any use to you.

If you end up being unable to solve the problem of server-side printing, then you could check out client-side drivers such as [qz](https://qz.io), which appears to be based on a Java plugin.

**Comment by digipifini** [comment] 2016-07-10 17:47
If you are using the network printer, you will simply need to direct incoming requests to the specific port, in my case 9100 then forward said port to the printer.  I have my printer hooked up to the usb port 1 of my Asus Router and printing works perfectly, however I have tested using additional USB printer servers and you need to be sure the one you use has 9100 available.  Not all of them do.

**Comment by mike42** [comment] 2016-10-04 09:44
Port forwarding is not great on its own- your receipts could be snooped, or any random on the Internet can print to your printer.

You really need a computer on the inside that can terminate an authenticated, secure tunnel. Use VPN, SSH, or TLS.

This query is now [listed in the FAQ](https://github.com/mike42/escpos-php/blob/development/doc/FAQ.md), so I'll close this off.

**Closed by mike42** 2016-10-04 09:44 UTC
Labels: duplicate, question

**Comment by mutiemule** [comment] 2022-04-30 10:46
Printing on local will work well with this package.

However, to print online, you will need to develop a desktop service which has to be installed on the local computer where you need printing to be done.  This is because PHP is a server-side scripting language, so once you put this online, it won't be able to communicate to the local printer. Thus, you need a client service running on the local machine and this is where electron js and node js come into play.

I resolved this by developing an electron js service based on [node-escpos package](https://www.npmjs.com/package/escpos) which can receive commands from the online print command and then communicate those commands to the printer through USB. 

Operating System does not matter in this case, you can be hosting on Linux based server and printing on a windows server. This desktop service interfaces between the online service and the local service. 

You can check out the [node-escpos printer driver package ](https://github.com/song940/node-escpos) for some inspiration on how to go about this.

Check the [FAQs on how to print online](https://github.com/mike42/escpos-php/blob/fe9350e61fb5e38416ec6243873c37fa65f34eb5/doc/FAQ.md#can-i-print-from-my-server-on-the-internet) to have some pointers too.
